[template]
src = "haproxy.cfg.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg"
keys = [
    "/emq/emqcl/nodes",
]
reload_cmd = "haproxy -f /usr/local/etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)"
